---
- name: Check if Sensuctl is already configured
  ansible.builtin.command: sensuctl --namespace {{ sensu_cli_namespace }} config view
  changed_when: false
  ignore_errors: true
  no_log: true
  register: _sensuctl_config

- name: Configure Sensuctl
  ansible.builtin.command: >
    sensuctl --namespace {{ sensu_cli_namespace }} configure
      -n
      --url {{ sensu_cli_backend_url }}
      --username {{ sensu_cli_username }}
      --password {{ sensu_cli_password }}
      --format {{ sensu_cli_format }}
  when: _sensuctl_config.rc != 0
