---
- name: Create users
  sensu.sensu_go.user:
    auth:
      password: "{{ sensu_cli_password }}"
      url: "{{ sensu_cli_backend_url }}"
      user: "{{ sensu_cli_username }}"
    groups: "{{ item.groups | d(omit) }}"
    name: "{{ item.name }}"
    password_hash: "{{ item.password_hash | d(omit) }}"
    password: "{{ item.password | d(omit) }}"
    state: enabled
  loop: "{{ sensu_cli_users }}"
  changed_when: false  # Required as the module fails to inform about changes when using a hash

- name: Create role bindings
  sensu.sensu_go.role_binding:
    auth:
      password: "{{ sensu_cli_password }}"
      url: "{{ sensu_cli_backend_url }}"
      user: "{{ sensu_cli_username }}"
    cluster_role: "{{ item.cluster_role | d(omit) }}"
    groups: "{{ item.groups | d(omit) }}"
    name: "{{ item.name }}"
    role: "{{ item.role | d(omit) }}"
    state: present
    users: "{{ item.users | d(omit) }}"
  loop: "{{ sensu_cli_role_bindings }}"
