---
dependency:
  name: galaxy
  options:
    role-file: molecule/shared/requirements.yml
    requirements-file: molecule/shared/requirements.yml
  env:
    ANSIBLE_ROLES_PATH: ../shared

driver:
  name: docker

provisioner:
  name: ansible
  playbooks:
    cleanup: ../shared/cleanup.yml
    converge: ../shared/converge.yml
    prepare: ../shared/prepare.yml

verifier:
  name: testinfra
  directory: ../shared/tests/
