---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-sensu-go-cli

      sensu_cli_assets:
        - name: sensu/sensu-slack-handler
          version: 1.0.3
        - name: sensu-plugins/sensu-plugins-cpu-checks
          rename: sensu-plugins-cpu-checks
          version: 4.1.0
        - name: sensu/sensu-ruby-runtime
          rename: sensu-ruby-runtime
          version: 0.0.10
        - name: sensu-plugins/sensu-plugins-http
          version: 6.0.0

      sensu_cli_pipe_handlers:
        - name: slack
          env_vars:
            SLACK_WEBHOOK_URL: https://hooks.slack.com/services/T0000/B000/XXXXXXXX
          command: sensu-slack-handler --channel '#monitoring'
          runtime_assets:
            - sensu-slack-handler

      sensu_cli_socket_handlers:
        - name: tcp_handler
          type: tcp
          host: 10.0.1.99
          port: 4444

      sensu_cli_handler_sets:
        - name: keepalive
          handlers:
            - slack

      sensu_cli_checks:
        - name: check-cpu-interval
          command: check-cpu.rb -w 75 -c 90
          interval: 60
          subscriptions:
            - system
          runtime_assets:
            - cpu-checks-plugins
            - sensu-ruby-runtime
        - name: check-cpu-cron
          command: check-cpu.rb -w 75 -c 90
          cron: '* * * * *'
          subscriptions:
            - system
          runtime_assets:
            - cpu-checks-plugins
            - sensu-ruby-runtime
        - name: check-cpu-ad-hoc
          command: check-cpu.rb -w 75 -c 90
          interval: 60
          publish: false
          subscriptions:
            - system
          runtime_assets:
            - cpu-checks-plugins
            - sensu-ruby-runtime
        - name: check-http-proxy
          command: http_check.sh https://sensu.io
          interval: 60
          proxy_entity_name: sensu-site
          round_robin: true
          subscriptions:
            - system
          runtime_assets:
            - sensu-plugins-http
            - sensu-ruby-runtime
